# Replicated using https://github.com/thornbill/jellyfin-web/blob/master/.github/workflows/build.yml

name: Build

on:
  push:
    branches: [ main, release* ]
  pull_request_target:
    branches: [ main, release* ]
  workflow_dispatch:

jobs:
  run-build-prod:
    name: Run production build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install nightly-2024-09-19 --profile minimal

      - run: rustup target add wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install Cargo Leptos
        run: curl --proto '=https' --tlsv1.2 -LsSf https://leptos-rs.artifacts.axodotdev.host/cargo-leptos/v0.2.20/cargo-leptos-installer.sh | sh

      - name: Build Web
        run: cargo leptos build --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website__prod
          path: target/site
          retention-days: 1
      - name: Upload websitebin 
        uses: actions/upload-artifact@v4
        with:
          name: website__prod_website_bin
          path: target/release/websitebin
          retention-days: 1


  generate_ssg:
    name: Generate SSG
    runs-on: ubuntu-latest
    needs:
      - run-build-prod
    permissions:
      contents: read
      deployments: write  
    
    steps:
      - uses: actions/checkout@v4

      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: website__prod
          path: target/site

      - name: Cache Images
        id: cache-images
        uses: actions/cache@v4
        with:
          path: target/images
          key: images

      - name: Download websitebin
        uses: actions/download-artifact@v4
        with:
          name: website__prod_website_bin

      - run: ls -l 
      - run: ls -l target
      - run: ls -l target/site
      - run: pwd
      - run: chmod +x websitebin

      - name: Generate SSG
        run: ./websitebin
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website__prod_ssg
          path: target/site
          retention-days: 1

      - name: List Images
        run: ls -l target/images

  generate_sitemap_previews:
    name: Generate sitemap and previews
    runs-on: ubuntu-latest
    needs:
      - generate_ssg
    permissions:
      contents: read
      deployments: write  
    
    steps:
      - run: rustup toolchain install stable --profile minimal

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1

      - uses: Swatinem/rust-cache@v2

      - name: Install leptos_sitemap
        run: cargo install --git https://github.com/deep-gaurav/leptos_sitemap.git
        
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: website__prod_ssg
          path: dist

      - name: Make Sitemap
        run: leptos_sitemap --dir dist --host "https://deepgaurav.com/"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website__prod_with_sitemap
          path: dist
          retention-days: 1


  publish:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'deep-gaurav/website' }}
    needs:
      - generate_sitemap_previews
    permissions:
      contents: read
      deployments: write  

    steps:
      - name: Add comment
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | 🔄 Deploying... |
            | **Preview URL**   | Not available |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: website__prod_with_sitemap
          path: dist

      - name: Publish to Cloudflare
        id: cf
        uses: cloudflare/wrangler-action@f84a562284fc78278ff9052435d9526f9c718361 # v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=website --branch=${{ github.ref_name }} --commit-hash=${{ github.event.pull_request.head.sha || github.sha }}

      - name: Update status comment (Success)
        if: ${{ github.event_name == 'pull_request_target' && success() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ✅ Deployed! |
            | **Preview URL**   | ${{ steps.cf.outputs.deployment-url != '' && steps.cf.outputs.deployment-url || 'Not available' }} |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Update status comment (Failure)
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ❌ Failure. Check workflow logs for details |
            | **Preview URL**   | Not available |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
